-- Shiprocket shipping (India-origin domestic + India-to-international only)

CREATE TABLE IF NOT EXISTS public.shipping_provider_settings (
  provider TEXT PRIMARY KEY,
  origin_country_iso2 CHAR(2) NOT NULL,
  api_base_url TEXT NOT NULL,
  domestic_serviceability_path TEXT NOT NULL,
  international_serviceability_path TEXT NOT NULL,
  auth_login_path TEXT NOT NULL,
  create_order_path TEXT NOT NULL,
  assign_awb_path TEXT NOT NULL,
  generate_label_path TEXT NOT NULL,
  generate_manifest_path TEXT NOT NULL,
  print_manifest_path TEXT NOT NULL,
  track_awb_path_template TEXT NOT NULL,
  is_enabled BOOLEAN NOT NULL DEFAULT true,
  supports_domestic BOOLEAN NOT NULL DEFAULT true,
  supports_international_from_origin BOOLEAN NOT NULL DEFAULT true,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.shipping_provider_settings (
  provider,
  origin_country_iso2,
  api_base_url,
  domestic_serviceability_path,
  international_serviceability_path,
  auth_login_path,
  create_order_path,
  assign_awb_path,
  generate_label_path,
  generate_manifest_path,
  print_manifest_path,
  track_awb_path_template
)
SELECT
  'shiprocket',
  c.iso_alpha2,
  'https://apiv2.shiprocket.in',
  '/v1/external/courier/serviceability/',
  '/v1/external/courier/international/serviceability',
  '/v1/external/auth/login',
  '/v1/external/orders/create/adhoc',
  '/v1/external/courier/assign/awb',
  '/v1/external/courier/generate/label',
  '/v1/external/manifests/generate',
  '/v1/external/manifests/print',
  '/v1/external/courier/track/awb/{awb_code}'
FROM public.countries c
WHERE c.iso_alpha2 = 'IN'
ON CONFLICT (provider) DO UPDATE
SET
  origin_country_iso2 = EXCLUDED.origin_country_iso2,
  api_base_url = EXCLUDED.api_base_url,
  domestic_serviceability_path = EXCLUDED.domestic_serviceability_path,
  international_serviceability_path = EXCLUDED.international_serviceability_path,
  auth_login_path = EXCLUDED.auth_login_path,
  create_order_path = EXCLUDED.create_order_path,
  assign_awb_path = EXCLUDED.assign_awb_path,
  generate_label_path = EXCLUDED.generate_label_path,
  generate_manifest_path = EXCLUDED.generate_manifest_path,
  print_manifest_path = EXCLUDED.print_manifest_path,
  track_awb_path_template = EXCLUDED.track_awb_path_template,
  updated_at = NOW();

CREATE TABLE IF NOT EXISTS public.shiprocket_auth_cache (
  provider TEXT PRIMARY KEY REFERENCES public.shipping_provider_settings (provider) ON DELETE CASCADE,
  access_token TEXT NOT NULL,
  company_id BIGINT,
  expires_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.seller_warehouses
  ADD COLUMN IF NOT EXISTS shiprocket_pickup_location_name TEXT;

ALTER TABLE public.seller_warehouses
  DROP CONSTRAINT IF EXISTS seller_warehouses_fields_not_empty;

ALTER TABLE public.seller_warehouses
  ADD CONSTRAINT seller_warehouses_fields_not_empty CHECK (
    BTRIM(warehouse_name) <> ''
    AND BTRIM(address_line) <> ''
    AND BTRIM(postal_code) <> ''
    AND dispatch_cutoff_time IS NOT NULL
  );

CREATE TYPE public.marketplace_order_status AS ENUM (
  'pending_seller_acceptance',
  'seller_rejected',
  'seller_accepted',
  'shiprocket_pending',
  'shiprocket_created',
  'packed',
  'shipped',
  'delivered',
  'cancelled'
);

CREATE TYPE public.marketplace_payment_method AS ENUM ('prepaid', 'cod');

CREATE TYPE public.shipping_lane AS ENUM ('india_domestic', 'india_international');

CREATE TABLE IF NOT EXISTS public.marketplace_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT NOT NULL UNIQUE,
  buyer_user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE RESTRICT,
  seller_user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE RESTRICT,
  status public.marketplace_order_status NOT NULL DEFAULT 'pending_seller_acceptance',
  payment_method public.marketplace_payment_method NOT NULL,
  shipping_lane public.shipping_lane NOT NULL,
  currency_code CHAR(3) NOT NULL REFERENCES public.countries (currency_code),
  subtotal_amount NUMERIC(12, 2) NOT NULL CHECK (subtotal_amount >= 0),
  shipping_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (shipping_amount >= 0),
  cod_charges_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (cod_charges_amount >= 0),
  tax_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
  total_amount NUMERIC(12, 2) NOT NULL CHECK (total_amount >= 0),
  pickup_postcode TEXT NOT NULL,
  delivery_full_name TEXT NOT NULL,
  delivery_phone TEXT NOT NULL,
  delivery_email TEXT NOT NULL,
  delivery_address_line1 TEXT NOT NULL,
  delivery_address_line2 TEXT,
  delivery_city TEXT NOT NULL,
  delivery_state TEXT NOT NULL,
  delivery_postcode TEXT NOT NULL,
  delivery_country_iso2 CHAR(2) NOT NULL,
  package_weight_kg NUMERIC(10, 3) NOT NULL CHECK (package_weight_kg > 0),
  package_length_cm NUMERIC(10, 2),
  package_width_cm NUMERIC(10, 2),
  package_height_cm NUMERIC(10, 2),
  shipping_courier_company_id BIGINT,
  shipping_courier_name TEXT,
  shipping_estimated_delivery TEXT,
  seller_response_note TEXT,
  seller_responded_at TIMESTAMPTZ,
  admin_shiprocket_pushed_at TIMESTAMPTZ,
  admin_shiprocket_pushed_by UUID REFERENCES auth.users (id),
  packed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS marketplace_orders_buyer_idx ON public.marketplace_orders (buyer_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS marketplace_orders_seller_idx ON public.marketplace_orders (seller_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS marketplace_orders_status_idx ON public.marketplace_orders (status);

CREATE TABLE IF NOT EXISTS public.marketplace_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES public.marketplace_orders (id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES public.seller_products (id) ON DELETE RESTRICT,
  variant_id BIGINT REFERENCES public.seller_product_variants (id) ON DELETE RESTRICT,
  product_name TEXT NOT NULL,
  sku TEXT NOT NULL,
  hsn_code TEXT,
  quantity INT NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
  line_total NUMERIC(12, 2) NOT NULL CHECK (line_total >= 0)
);

CREATE INDEX IF NOT EXISTS marketplace_order_items_order_idx ON public.marketplace_order_items (order_id);

CREATE TABLE IF NOT EXISTS public.marketplace_order_shipments (
  order_id BIGINT PRIMARY KEY REFERENCES public.marketplace_orders (id) ON DELETE CASCADE,
  provider TEXT NOT NULL REFERENCES public.shipping_provider_settings (provider),
  shiprocket_order_id BIGINT,
  shiprocket_shipment_id BIGINT,
  awb_code TEXT,
  label_url TEXT,
  manifest_url TEXT,
  tracking_payload JSONB,
  last_tracked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION public.is_india_origin_seller(p_seller_user_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.seller_accounts sa
    JOIN public.shipping_provider_settings sps ON sps.provider = 'shiprocket' AND sps.is_enabled
    WHERE sa.user_id = p_seller_user_id
      AND sa.iso_alpha2 = sps.origin_country_iso2
  );
$$;

CREATE OR REPLACE FUNCTION public.resolve_shipping_lane(
  p_origin_iso2 CHAR(2),
  p_delivery_iso2 CHAR(2)
)
RETURNS public.shipping_lane
LANGUAGE plpgsql
STABLE
SET search_path = public
AS $$
BEGIN
  IF p_origin_iso2 IS DISTINCT FROM (SELECT origin_country_iso2 FROM public.shipping_provider_settings WHERE provider = 'shiprocket' AND is_enabled) THEN
    RAISE EXCEPTION 'Only India-origin seller shipments are supported.';
  END IF;

  IF p_delivery_iso2 = p_origin_iso2 THEN
    RETURN 'india_domestic';
  END IF;

  RETURN 'india_international';
END;
$$;

CREATE OR REPLACE FUNCTION public.generate_marketplace_order_number()
RETURNS TEXT
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  v_seq BIGINT;
BEGIN
  SELECT COALESCE(MAX(id), 0) + 1 INTO v_seq FROM public.marketplace_orders;
  RETURN 'AGT-' || TO_CHAR(NOW() AT TIME ZONE 'UTC', 'YYYYMMDD') || '-' || LPAD(v_seq::TEXT, 6, '0');
END;
$$;

CREATE OR REPLACE FUNCTION public.create_marketplace_order(
  p_seller_user_id UUID,
  p_payment_method public.marketplace_payment_method,
  p_currency_code CHAR(3),
  p_subtotal NUMERIC,
  p_shipping_amount NUMERIC,
  p_cod_charges_amount NUMERIC,
  p_tax_amount NUMERIC,
  p_total_amount NUMERIC,
  p_delivery JSONB,
  p_shipping_quote JSONB,
  p_items JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_buyer UUID := auth.uid();
  v_order_id BIGINT;
  v_order_number TEXT;
  v_lane public.shipping_lane;
  v_origin_iso2 CHAR(2);
  v_pickup_postcode TEXT;
  v_item JSONB;
  v_product public.seller_products%ROWTYPE;
BEGIN
  IF v_buyer IS NULL THEN
    RAISE EXCEPTION 'Authentication required.';
  END IF;

  IF NOT public.is_india_origin_seller(p_seller_user_id) THEN
    RAISE EXCEPTION 'Shiprocket shipping is only available for India-origin sellers.';
  END IF;

  SELECT sa.iso_alpha2 INTO v_origin_iso2
  FROM public.seller_accounts sa
  WHERE sa.user_id = p_seller_user_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Seller account not found.';
  END IF;

  SELECT w.postal_code
  INTO v_pickup_postcode
  FROM public.seller_warehouses w
  WHERE w.user_id = p_seller_user_id
    AND w.is_completed = true;

  IF v_pickup_postcode IS NULL THEN
    RAISE EXCEPTION 'Seller warehouse pickup postcode is not configured.';
  END IF;

  v_lane := public.resolve_shipping_lane(v_origin_iso2, upper(btrim(p_delivery->>'countryIso2'))::CHAR(2));

  IF v_lane = 'india_international' AND p_payment_method = 'cod' THEN
    RAISE EXCEPTION 'Cash on delivery is not available for international shipments.';
  END IF;

  IF v_lane = 'india_domestic' AND p_payment_method = 'cod' AND COALESCE((p_shipping_quote->>'codAvailable')::BOOLEAN, false) IS NOT TRUE THEN
    RAISE EXCEPTION 'Cash on delivery is not serviceable for this domestic address.';
  END IF;

  v_order_number := public.generate_marketplace_order_number();

  INSERT INTO public.marketplace_orders (
    order_number,
    buyer_user_id,
    seller_user_id,
    payment_method,
    shipping_lane,
    currency_code,
    subtotal_amount,
    shipping_amount,
    cod_charges_amount,
    tax_amount,
    total_amount,
    pickup_postcode,
    delivery_full_name,
    delivery_phone,
    delivery_email,
    delivery_address_line1,
    delivery_address_line2,
    delivery_city,
    delivery_state,
    delivery_postcode,
    delivery_country_iso2,
    package_weight_kg,
    package_length_cm,
    package_width_cm,
    package_height_cm,
    shipping_courier_company_id,
    shipping_courier_name,
    shipping_estimated_delivery
  )
  VALUES (
    v_order_number,
    v_buyer,
    p_seller_user_id,
    p_payment_method,
    v_lane,
    upper(p_currency_code),
    p_subtotal,
    p_shipping_amount,
    COALESCE(p_cod_charges_amount, 0),
    p_tax_amount,
    p_total_amount,
    v_pickup_postcode,
    btrim(p_delivery->>'fullName'),
    btrim(p_delivery->>'phone'),
    lower(btrim(p_delivery->>'email')),
    btrim(p_delivery->>'addressLine1'),
    NULLIF(btrim(p_delivery->>'addressLine2'), ''),
    btrim(p_delivery->>'city'),
    btrim(p_delivery->>'state'),
    btrim(p_delivery->>'postcode'),
    upper(btrim(p_delivery->>'countryIso2'))::CHAR(2),
    (p_shipping_quote->>'weightKg')::NUMERIC,
    NULLIF(p_shipping_quote->>'lengthCm', '')::NUMERIC,
    NULLIF(p_shipping_quote->>'widthCm', '')::NUMERIC,
    NULLIF(p_shipping_quote->>'heightCm', '')::NUMERIC,
    NULLIF(p_shipping_quote->>'courierCompanyId', '')::BIGINT,
    NULLIF(p_shipping_quote->>'courierName', ''),
    NULLIF(p_shipping_quote->>'estimatedDelivery', '')
  )
  RETURNING id INTO v_order_id;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    SELECT * INTO v_product
    FROM public.seller_products
    WHERE id = (v_item->>'productId')::BIGINT
      AND user_id = p_seller_user_id
      AND approval_status = 'approved';

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Product % is not available from this seller.', v_item->>'productId';
    END IF;

    INSERT INTO public.marketplace_order_items (
      order_id,
      product_id,
      variant_id,
      product_name,
      sku,
      hsn_code,
      quantity,
      unit_price,
      line_total
    )
    VALUES (
      v_order_id,
      v_product.id,
      NULLIF(v_item->>'variantId', '')::BIGINT,
      v_product.product_name,
      COALESCE(NULLIF(v_item->>'sku', ''), v_product.sku),
      v_product.hsn_code,
      (v_item->>'quantity')::INT,
      (v_item->>'unitPrice')::NUMERIC,
      (v_item->>'lineTotal')::NUMERIC
    );
  END LOOP;

  RETURN jsonb_build_object(
    'ok', true,
    'orderId', v_order_id,
    'orderNumber', v_order_number,
    'shippingLane', v_lane::TEXT
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.seller_respond_marketplace_order(
  p_order_id BIGINT,
  p_accept BOOLEAN,
  p_note TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_order public.marketplace_orders%ROWTYPE;
BEGIN
  SELECT * INTO v_order
  FROM public.marketplace_orders
  WHERE id = p_order_id
    AND seller_user_id = auth.uid();

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Order not found.';
  END IF;

  IF v_order.status <> 'pending_seller_acceptance' THEN
    RAISE EXCEPTION 'Order is not awaiting seller response.';
  END IF;

  UPDATE public.marketplace_orders
  SET
    status = CASE WHEN p_accept THEN 'seller_accepted' ELSE 'seller_rejected' END,
    seller_response_note = NULLIF(btrim(p_note), ''),
    seller_responded_at = NOW(),
    updated_at = NOW()
  WHERE id = p_order_id;

  RETURN jsonb_build_object(
    'ok', true,
    'status', CASE WHEN p_accept THEN 'seller_accepted' ELSE 'seller_rejected' END
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_mark_shiprocket_pending(p_order_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_order public.marketplace_orders%ROWTYPE;
BEGIN
  IF NOT public.is_admin_account() THEN
    RAISE EXCEPTION 'Admin access required.';
  END IF;

  SELECT * INTO v_order FROM public.marketplace_orders WHERE id = p_order_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Order not found.';
  END IF;

  IF v_order.status <> 'seller_accepted' THEN
    RAISE EXCEPTION 'Order must be seller-accepted before Shiprocket push.';
  END IF;

  UPDATE public.marketplace_orders
  SET status = 'shiprocket_pending', updated_at = NOW()
  WHERE id = p_order_id;

  RETURN jsonb_build_object('ok', true, 'status', 'shiprocket_pending');
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_complete_shiprocket_push(
  p_order_id BIGINT,
  p_shiprocket_order_id BIGINT,
  p_shiprocket_shipment_id BIGINT,
  p_awb_code TEXT,
  p_label_url TEXT DEFAULT NULL,
  p_manifest_url TEXT DEFAULT NULL,
  p_courier_name TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_admin_account() THEN
    RAISE EXCEPTION 'Admin access required.';
  END IF;

  UPDATE public.marketplace_orders
  SET
    status = 'shiprocket_created',
    admin_shiprocket_pushed_at = NOW(),
    admin_shiprocket_pushed_by = auth.uid(),
    shipping_courier_name = COALESCE(p_courier_name, shipping_courier_name),
    updated_at = NOW()
  WHERE id = p_order_id
    AND status IN ('seller_accepted', 'shiprocket_pending');

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Order is not ready for Shiprocket completion.';
  END IF;

  INSERT INTO public.marketplace_order_shipments (
    order_id,
    provider,
    shiprocket_order_id,
    shiprocket_shipment_id,
    awb_code,
    label_url,
    manifest_url
  )
  VALUES (
    p_order_id,
    'shiprocket',
    p_shiprocket_order_id,
    p_shiprocket_shipment_id,
    NULLIF(btrim(p_awb_code), ''),
    NULLIF(btrim(p_label_url), ''),
    NULLIF(btrim(p_manifest_url), '')
  )
  ON CONFLICT (order_id) DO UPDATE
  SET
    shiprocket_order_id = EXCLUDED.shiprocket_order_id,
    shiprocket_shipment_id = EXCLUDED.shiprocket_shipment_id,
    awb_code = EXCLUDED.awb_code,
    label_url = COALESCE(EXCLUDED.label_url, marketplace_order_shipments.label_url),
    manifest_url = COALESCE(EXCLUDED.manifest_url, marketplace_order_shipments.manifest_url),
    updated_at = NOW();

  RETURN jsonb_build_object('ok', true, 'status', 'shiprocket_created');
END;
$$;

CREATE OR REPLACE FUNCTION public.seller_mark_order_packed(p_order_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.marketplace_orders
  SET status = 'packed', packed_at = NOW(), updated_at = NOW()
  WHERE id = p_order_id
    AND seller_user_id = auth.uid()
    AND status = 'shiprocket_created';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Order must be Shiprocket-created before marking packed.';
  END IF;

  RETURN jsonb_build_object('ok', true, 'status', 'packed');
END;
$$;

CREATE OR REPLACE FUNCTION public.update_shipment_documents(
  p_order_id BIGINT,
  p_label_url TEXT,
  p_manifest_url TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.marketplace_order_shipments
  SET
    label_url = NULLIF(btrim(p_label_url), ''),
    manifest_url = NULLIF(btrim(p_manifest_url), ''),
    updated_at = NOW()
  WHERE order_id = p_order_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Shipment not found.';
  END IF;

  RETURN jsonb_build_object('ok', true);
END;
$$;

CREATE OR REPLACE FUNCTION public.update_shipment_tracking(
  p_order_id BIGINT,
  p_tracking_payload JSONB,
  p_mark_shipped BOOLEAN DEFAULT false
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.marketplace_order_shipments
  SET
    tracking_payload = p_tracking_payload,
    last_tracked_at = NOW(),
    updated_at = NOW()
  WHERE order_id = p_order_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Shipment not found.';
  END IF;

  IF p_mark_shipped THEN
    UPDATE public.marketplace_orders
    SET status = 'shipped', updated_at = NOW()
    WHERE id = p_order_id
      AND status IN ('packed', 'shiprocket_created');
  END IF;

  RETURN jsonb_build_object('ok', true);
END;
$$;

DROP TRIGGER IF EXISTS marketplace_orders_set_updated_at ON public.marketplace_orders;
CREATE TRIGGER marketplace_orders_set_updated_at
BEFORE UPDATE ON public.marketplace_orders
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS marketplace_order_shipments_set_updated_at ON public.marketplace_order_shipments;
CREATE TRIGGER marketplace_order_shipments_set_updated_at
BEFORE UPDATE ON public.marketplace_order_shipments
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.shipping_provider_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shiprocket_auth_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketplace_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketplace_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketplace_order_shipments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read shipping provider settings" ON public.shipping_provider_settings;
CREATE POLICY "Public read shipping provider settings"
ON public.shipping_provider_settings
FOR SELECT
TO anon, authenticated
USING (is_enabled);

DROP POLICY IF EXISTS "Buyers read own orders" ON public.marketplace_orders;
CREATE POLICY "Buyers read own orders"
ON public.marketplace_orders
FOR SELECT
TO authenticated
USING (buyer_user_id = auth.uid());

DROP POLICY IF EXISTS "Sellers read own orders" ON public.marketplace_orders;
CREATE POLICY "Sellers read own orders"
ON public.marketplace_orders
FOR SELECT
TO authenticated
USING (seller_user_id = auth.uid());

DROP POLICY IF EXISTS "Admins read orders" ON public.marketplace_orders;
CREATE POLICY "Admins read orders"
ON public.marketplace_orders
FOR SELECT
TO authenticated
USING (public.is_admin_account());

DROP POLICY IF EXISTS "Order items via order access" ON public.marketplace_order_items;
CREATE POLICY "Order items via order access"
ON public.marketplace_order_items
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.marketplace_orders o
    WHERE o.id = order_id
      AND (
        o.buyer_user_id = auth.uid()
        OR o.seller_user_id = auth.uid()
        OR public.is_admin_account()
      )
  )
);

DROP POLICY IF EXISTS "Shipments via order access" ON public.marketplace_order_shipments;
CREATE POLICY "Shipments via order access"
ON public.marketplace_order_shipments
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.marketplace_orders o
    WHERE o.id = order_id
      AND (
        o.buyer_user_id = auth.uid()
        OR o.seller_user_id = auth.uid()
        OR public.is_admin_account()
      )
  )
);

REVOKE ALL ON FUNCTION public.is_india_origin_seller(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.resolve_shipping_lane(CHAR(2), CHAR(2)) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.generate_marketplace_order_number() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_marketplace_order(UUID, public.marketplace_payment_method, CHAR(3), NUMERIC, NUMERIC, NUMERIC, NUMERIC, NUMERIC, JSONB, JSONB, JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.seller_respond_marketplace_order(BIGINT, BOOLEAN, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_mark_shiprocket_pending(BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_complete_shiprocket_push(BIGINT, BIGINT, BIGINT, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.seller_mark_order_packed(BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.update_shipment_documents(BIGINT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.update_shipment_tracking(BIGINT, JSONB, BOOLEAN) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.is_india_origin_seller(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_marketplace_order(UUID, public.marketplace_payment_method, CHAR(3), NUMERIC, NUMERIC, NUMERIC, NUMERIC, NUMERIC, JSONB, JSONB, JSONB) TO authenticated;
GRANT EXECUTE ON FUNCTION public.seller_respond_marketplace_order(BIGINT, BOOLEAN, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_mark_shiprocket_pending(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_complete_shiprocket_push(BIGINT, BIGINT, BIGINT, TEXT, TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.seller_mark_order_packed(BIGINT) TO authenticated;

GRANT SELECT ON public.shipping_provider_settings TO anon, authenticated;
GRANT SELECT ON public.marketplace_orders TO authenticated;
GRANT SELECT ON public.marketplace_order_items TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_shipment_documents(BIGINT, TEXT, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.update_shipment_tracking(BIGINT, JSONB, BOOLEAN) TO service_role;
