-- Stripe global payments for marketplace prepaid orders

CREATE TYPE public.marketplace_payment_status AS ENUM (
  'not_required',
  'pending',
  'paid',
  'failed',
  'refunded'
);

ALTER TABLE public.marketplace_orders
  ADD COLUMN IF NOT EXISTS payment_status public.marketplace_payment_status NOT NULL DEFAULT 'not_required',
  ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ;

UPDATE public.marketplace_orders
SET payment_status = CASE
  WHEN payment_method = 'cod' THEN 'not_required'::public.marketplace_payment_status
  ELSE 'paid'::public.marketplace_payment_status
END;

CREATE TABLE IF NOT EXISTS public.payment_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES public.marketplace_orders (id) ON DELETE CASCADE,
  provider TEXT NOT NULL DEFAULT 'stripe',
  stripe_checkout_session_id TEXT NOT NULL UNIQUE,
  stripe_payment_intent_id TEXT,
  amount_minor BIGINT NOT NULL CHECK (amount_minor > 0),
  currency_code CHAR(3) NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  raw_payload JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS payment_transactions_order_idx ON public.payment_transactions (order_id);

CREATE OR REPLACE FUNCTION public.create_marketplace_order(
  p_seller_user_id UUID,
  p_payment_method public.marketplace_payment_method,
  p_currency_code CHAR(3),
  p_subtotal NUMERIC,
  p_shipping_amount NUMERIC,
  p_cod_charges_amount NUMERIC,
  p_tax_amount NUMERIC,
  p_total_amount NUMERIC,
  p_delivery JSONB,
  p_shipping_quote JSONB,
  p_items JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_buyer UUID := auth.uid();
  v_order_id BIGINT;
  v_order_number TEXT;
  v_lane public.shipping_lane;
  v_origin_iso2 CHAR(2);
  v_pickup_postcode TEXT;
  v_item JSONB;
  v_product public.seller_products%ROWTYPE;
  v_order_status public.marketplace_order_status;
  v_payment_status public.marketplace_payment_status;
BEGIN
  IF v_buyer IS NULL THEN
    RAISE EXCEPTION 'Authentication required.';
  END IF;

  IF NOT public.is_india_origin_seller(p_seller_user_id) THEN
    RAISE EXCEPTION 'Shiprocket shipping is only available for India-origin sellers.';
  END IF;

  SELECT sa.iso_alpha2 INTO v_origin_iso2
  FROM public.seller_accounts sa
  WHERE sa.user_id = p_seller_user_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Seller account not found.';
  END IF;

  SELECT w.postal_code
  INTO v_pickup_postcode
  FROM public.seller_warehouses w
  WHERE w.user_id = p_seller_user_id
    AND w.is_completed = true;

  IF v_pickup_postcode IS NULL THEN
    RAISE EXCEPTION 'Seller warehouse pickup postcode is not configured.';
  END IF;

  v_lane := public.resolve_shipping_lane(v_origin_iso2, upper(btrim(p_delivery->>'countryIso2'))::CHAR(2));

  IF v_lane = 'india_international' AND p_payment_method = 'cod' THEN
    RAISE EXCEPTION 'Cash on delivery is not available for international shipments.';
  END IF;

  IF v_lane = 'india_domestic' AND p_payment_method = 'cod' AND COALESCE((p_shipping_quote->>'codAvailable')::BOOLEAN, false) IS NOT TRUE THEN
    RAISE EXCEPTION 'Cash on delivery is not serviceable for this domestic address.';
  END IF;

  IF p_payment_method = 'prepaid' THEN
    v_order_status := 'awaiting_payment';
    v_payment_status := 'pending';
  ELSE
    v_order_status := 'pending_seller_acceptance';
    v_payment_status := 'not_required';
  END IF;

  v_order_number := public.generate_marketplace_order_number();

  INSERT INTO public.marketplace_orders (
    order_number,
    buyer_user_id,
    seller_user_id,
    status,
    payment_method,
    payment_status,
    shipping_lane,
    currency_code,
    subtotal_amount,
    shipping_amount,
    cod_charges_amount,
    tax_amount,
    total_amount,
    pickup_postcode,
    delivery_full_name,
    delivery_phone,
    delivery_email,
    delivery_address_line1,
    delivery_address_line2,
    delivery_city,
    delivery_state,
    delivery_postcode,
    delivery_country_iso2,
    package_weight_kg,
    package_length_cm,
    package_width_cm,
    package_height_cm,
    shipping_courier_company_id,
    shipping_courier_name,
    shipping_estimated_delivery
  )
  VALUES (
    v_order_number,
    v_buyer,
    p_seller_user_id,
    v_order_status,
    p_payment_method,
    v_payment_status,
    v_lane,
    upper(p_currency_code),
    p_subtotal,
    p_shipping_amount,
    COALESCE(p_cod_charges_amount, 0),
    p_tax_amount,
    p_total_amount,
    v_pickup_postcode,
    btrim(p_delivery->>'fullName'),
    btrim(p_delivery->>'phone'),
    lower(btrim(p_delivery->>'email')),
    btrim(p_delivery->>'addressLine1'),
    NULLIF(btrim(p_delivery->>'addressLine2'), ''),
    btrim(p_delivery->>'city'),
    btrim(p_delivery->>'state'),
    btrim(p_delivery->>'postcode'),
    upper(btrim(p_delivery->>'countryIso2'))::CHAR(2),
    (p_shipping_quote->>'weightKg')::NUMERIC,
    NULLIF(p_shipping_quote->>'lengthCm', '')::NUMERIC,
    NULLIF(p_shipping_quote->>'widthCm', '')::NUMERIC,
    NULLIF(p_shipping_quote->>'heightCm', '')::NUMERIC,
    NULLIF(p_shipping_quote->>'courierCompanyId', '')::BIGINT,
    NULLIF(p_shipping_quote->>'courierName', ''),
    NULLIF(p_shipping_quote->>'estimatedDelivery', '')
  )
  RETURNING id INTO v_order_id;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    SELECT * INTO v_product
    FROM public.seller_products
    WHERE id = (v_item->>'productId')::BIGINT
      AND user_id = p_seller_user_id
      AND approval_status = 'approved';

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Product % is not available from this seller.', v_item->>'productId';
    END IF;

    INSERT INTO public.marketplace_order_items (
      order_id,
      product_id,
      variant_id,
      product_name,
      sku,
      hsn_code,
      quantity,
      unit_price,
      line_total
    )
    VALUES (
      v_order_id,
      v_product.id,
      NULLIF(v_item->>'variantId', '')::BIGINT,
      v_product.product_name,
      COALESCE(NULLIF(v_item->>'sku', ''), v_product.sku),
      v_product.hsn_code,
      (v_item->>'quantity')::INT,
      (v_item->>'unitPrice')::NUMERIC,
      (v_item->>'lineTotal')::NUMERIC
    );
  END LOOP;

  RETURN jsonb_build_object(
    'ok', true,
    'orderId', v_order_id,
    'orderNumber', v_order_number,
    'shippingLane', v_lane::TEXT,
    'requiresPayment', p_payment_method = 'prepaid'
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.record_stripe_checkout_session(
  p_order_id BIGINT,
  p_stripe_checkout_session_id TEXT,
  p_amount_minor BIGINT,
  p_currency_code CHAR(3)
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_order public.marketplace_orders%ROWTYPE;
BEGIN
  SELECT * INTO v_order
  FROM public.marketplace_orders
  WHERE id = p_order_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Order not found.';
  END IF;

  IF v_order.status <> 'awaiting_payment' OR v_order.payment_status <> 'pending' THEN
    RAISE EXCEPTION 'Order is not awaiting Stripe payment.';
  END IF;

  IF upper(v_order.currency_code) <> upper(p_currency_code) THEN
    RAISE EXCEPTION 'Stripe currency does not match order currency.';
  END IF;

  INSERT INTO public.payment_transactions (
    order_id,
    provider,
    stripe_checkout_session_id,
    amount_minor,
    currency_code,
    status
  )
  VALUES (
    p_order_id,
    'stripe',
    p_stripe_checkout_session_id,
    p_amount_minor,
    upper(p_currency_code),
    'pending'
  )
  ON CONFLICT (stripe_checkout_session_id) DO UPDATE
  SET
    amount_minor = EXCLUDED.amount_minor,
    currency_code = EXCLUDED.currency_code,
    updated_at = NOW();

  RETURN jsonb_build_object('ok', true);
END;
$$;

CREATE OR REPLACE FUNCTION public.confirm_marketplace_stripe_payment(
  p_order_id BIGINT,
  p_stripe_checkout_session_id TEXT,
  p_stripe_payment_intent_id TEXT,
  p_amount_minor BIGINT,
  p_currency_code CHAR(3),
  p_raw_payload JSONB DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_order public.marketplace_orders%ROWTYPE;
BEGIN
  SELECT * INTO v_order
  FROM public.marketplace_orders
  WHERE id = p_order_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Order not found.';
  END IF;

  IF v_order.status = 'pending_seller_acceptance' AND v_order.payment_status = 'paid' THEN
    RETURN jsonb_build_object('ok', true, 'orderNumber', v_order.order_number, 'alreadyConfirmed', true);
  END IF;

  IF v_order.status <> 'awaiting_payment' OR v_order.payment_status <> 'pending' THEN
    RAISE EXCEPTION 'Order is not awaiting Stripe payment.';
  END IF;

  IF upper(v_order.currency_code) <> upper(p_currency_code) THEN
    RAISE EXCEPTION 'Stripe currency does not match order currency.';
  END IF;

  UPDATE public.marketplace_orders
  SET
    status = 'pending_seller_acceptance',
    payment_status = 'paid',
    paid_at = NOW(),
    updated_at = NOW()
  WHERE id = p_order_id;

  UPDATE public.payment_transactions
  SET
    stripe_payment_intent_id = p_stripe_payment_intent_id,
    amount_minor = p_amount_minor,
    currency_code = upper(p_currency_code),
    status = 'succeeded',
    raw_payload = COALESCE(p_raw_payload, raw_payload),
    updated_at = NOW()
  WHERE stripe_checkout_session_id = p_stripe_checkout_session_id;

  IF NOT FOUND THEN
    INSERT INTO public.payment_transactions (
      order_id,
      provider,
      stripe_checkout_session_id,
      stripe_payment_intent_id,
      amount_minor,
      currency_code,
      status,
      raw_payload
    )
    VALUES (
      p_order_id,
      'stripe',
      p_stripe_checkout_session_id,
      p_stripe_payment_intent_id,
      p_amount_minor,
      upper(p_currency_code),
      'succeeded',
      p_raw_payload
    );
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'orderNumber', v_order.order_number,
    'orderId', v_order.id
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.fail_marketplace_stripe_payment(
  p_order_id BIGINT,
  p_stripe_checkout_session_id TEXT,
  p_raw_payload JSONB DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.marketplace_orders
  SET
    status = 'cancelled',
    payment_status = 'failed',
    updated_at = NOW()
  WHERE id = p_order_id
    AND status = 'awaiting_payment'
    AND payment_status = 'pending';

  UPDATE public.payment_transactions
  SET
    status = 'failed',
    raw_payload = COALESCE(p_raw_payload, raw_payload),
    updated_at = NOW()
  WHERE stripe_checkout_session_id = p_stripe_checkout_session_id;

  RETURN jsonb_build_object('ok', true);
END;
$$;

ALTER TABLE public.payment_transactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Buyers read own payment transactions" ON public.payment_transactions;
CREATE POLICY "Buyers read own payment transactions"
ON public.payment_transactions
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.marketplace_orders o
    WHERE o.id = order_id
      AND (
        o.buyer_user_id = auth.uid()
        OR o.seller_user_id = auth.uid()
        OR public.is_admin_account()
      )
  )
);

REVOKE ALL ON FUNCTION public.record_stripe_checkout_session(BIGINT, TEXT, BIGINT, CHAR(3)) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.confirm_marketplace_stripe_payment(BIGINT, TEXT, TEXT, BIGINT, CHAR(3), JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.fail_marketplace_stripe_payment(BIGINT, TEXT, JSONB) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.record_stripe_checkout_session(BIGINT, TEXT, BIGINT, CHAR(3)) TO service_role;
GRANT EXECUTE ON FUNCTION public.confirm_marketplace_stripe_payment(BIGINT, TEXT, TEXT, BIGINT, CHAR(3), JSONB) TO service_role;
GRANT EXECUTE ON FUNCTION public.fail_marketplace_stripe_payment(BIGINT, TEXT, JSONB) TO service_role;
